[mgr]
cwd = { fg = "blue" }
preview_hovered = { fg = "cyan" }

[filetype]
rules = [
	{ mime = "audio/*", fg = "red" },
	{ mime = "image/*", fg = "green" },
	{ mime = "video/*", fg = "yellow" },
]

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
