[mgr]
cwd = { fg = "blue" }
preview_hovered = { fg = "cyan" }

[filetype]
rules = [
	{ mime = "audio/*", fg = "red" },
	{ mime = "image/*", fg = "green" },
	{ mime = "video/*", fg = "yellow" },
]

[icon]
globs = [
    { url = "*/", text = "" },
    { url = "*", text = "" }
]
dirs = []
files = []
exts  = []
conds = []
