[mgr]
ratio = [1, 3, 2]
sort_by = "natural"
show_hidden = true

[preview]
tab_size = 4

[opener]
aseprite = [{ run = 'aseprite "$@"', orphan = true }]
inkscape = [{ run = 'inkscape "$@"', orphan = true }]
mpv = [{ run = 'mpv "$@"', orphan = true }]
nvim = [{ run = 'nvim "$@"', block = true }]
paplay = [{ run = 'paplay "$@"', orphan = true }]
awww = [{ run = 'awww img "$@" -tcenter', orphan = true }]
awww_pixel = [{ desc = "awww pixel", run = 'awww img "$@" -tcenter -fNearest', orphan = true }]
sioyek = [{ run = 'sioyek "$@"', orphan = true }]
unzip = [{ run = 'unzip "$@" -x __M*' }]
untar = [{ run = 'tar xzf "$@"' }]
zen = [{ run = 'zen-browser "$@"', orphan = true }]

[open]
rules = [
    {mime = "application/pdf", use = ["sioyek"]},
    {mime = "application/zip", use = ["unzip"]},

    {mime = "audio/*", use = ["paplay"]},
    {mime = "image/*", use = ["aseprite", "awww", "awww_pixel", "zen"]},
    {mime = "video/*", use = ["mpv"]},

    {url = "*.svg", use = ["inkscape", "zen"]},
    {url = "*.html", use = ["zen", "nvim"]},
    {url = "*/", use = ["nvim"]},
    {url = "*", use = ["nvim"]}
]
