tick_rate = 50
default_channel = "files"

history_size = 0
global_history = false

[ui]
ui_scale = 100
orientation = "landscape"
theme = "catppuccin-mocha-blue.toml"

[ui.input_bar]
prompt = ">"
position = "top"
border_type = "rounded"

[ui.status_bar]
hidden = true

[ui.results_panel]
border_type = "rounded"

[ui.preview_panel]
size = 50
scrollbar = true
border_type = "rounded"
hidden = false

[ui.help_panel]
show_categories = true
hidden = true

[ui.remote_control]
sort_alphabetically = true
show_channel_descriptions = true

[keybindings]
esc = "quit"
ctrl-j = "select_next_entry"
ctrl-k = "select_prev_entry"
tab = "toggle_selection_down"
enter = "confirm_selection"
pagedown = "scroll_preview_half_page_down"
pageup = "scroll_preview_half_page_up"
ctrl-f = "cycle_previews"
ctrl-t = "toggle_remote_control"
ctrl-x = "toggle_action_picker"
ctrl-shift-p = "toggle_preview"
ctrl-shift-h = "toggle_help"
ctrl-shift-l = "toggle_layout"
backspace = "delete_prev_char"

[shell_integration.channel_triggers]
"dirs" = ["cd", "ls"]
"files" = ["cat", "mv", "cp", "nvim"]
